# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='code')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(max_length=100, verbose_name='description')),
                ('applicable_from', models.DateField(help_text='price applies from date', verbose_name='applicable from')),
                ('applicable_to', models.DateField(help_text='price applies to date', verbose_name='applicable to')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='gross amount')),
                ('reimbursed', models.BooleanField(default=True, help_text='care can be reimbursed by NHS', verbose_name='reimbursed')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_contract', models.DateField(verbose_name='start date')),
                ('end_contract', models.DateField(blank=True, null=True, verbose_name='end date')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPresciption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.ImageField(upload_to='scans')),
                ('startDate', models.DateField(verbose_name='start date prescription')),
                ('endDate', models.DateField(verbose_name='end date prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sn', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_address', models.EmailField(blank=True, default=None, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ns', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=30)),
                ('zipcode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='service date')),
                ('carecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiomultiv2.CareCode')),
            ],
        ),
        migrations.AddField(
            model_name='medicalpresciption',
            name='practician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiomultiv2.Practian'),
        ),
        migrations.AddField(
            model_name='employee',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiomultiv2.JobPosition'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
